Financing budgeting/fin 29 receivables
titancamp/travely-client pull request #83
Opened 2022-01-21 21:50 UTC by tatul-m

Please ignore all issues which same as in Payables.
Waiting for their resolving to merge

2022-01-22 16:54 UTC, igortokhunts approved these changes

2022-01-24 13:26 UTC, TigranYengiba04 requested changes

2022-01-24 13:26 UTC, TigranYengiba04 commented on src/src_V2/modules/manager/financial/components/receivables/Receivables.jsx
> +      (item) =>
I think this approach will be more readable: `({ tourName, receivableId, partner }) => [tourName, receivableId, partner].some(item => item.toLowerCase().includes(searchTxt))`

2022-01-24 13:26 UTC, TigranYengiba04 commented on src/src_V2/modules/manager/financial/components/receivables/Receivables.jsx
> +    <>
pls remove fragment

2022-01-24 13:26 UTC, TigranYengiba04 commented on src/src_V2/modules/manager/financial/components/receivables/edit/drawer-content/notes/Notes.jsx
> +                  <p>{!!values?.notes?.length && `${values.notes.length}/500 letter`}</p>
pls use Typography

2022-01-24 13:26 UTC, TigranYengiba04 commented on src/src_V2/modules/manager/financial/components/receivables/edit/drawer/EditDrawer.jsx
> +  const toggleDrawer = (isOpened) => {
pls remove isOpened argument and get it from drawerState

2022-01-24 14:51 UTC, merged