Reporting and Dashboards UI improvements
titancamp/travely-client pull request #87
Opened 2022-01-26 18:29 UTC by TigranYengiba04

2022-01-26 20:17 UTC, igortokhunts approved these changes

2022-01-27 08:59 UTC, sasuntitan requested changes

2022-01-27 08:59 UTC, sasuntitan commented on src/src_V2/modules/manager/dashboard/index.jsx
> +          <Button variant='text' color='primary'>
please make this link to redirect to list page

2022-01-30 19:44 UTC, sasuntitan approved these changes

2022-01-30 19:44 UTC, merged